### ISSUE TITLE
Давайте теперь исправлять

### ISSUE THREAD

**Issue by 3s3s** [Zigridar/bitcoin-0.12.1#2]
Ну вот у вас в архиве код биткоина. Если его скомпилировать, то он начнет синхронизацию с биткоином.
Исправьте теперь coinbase чтобы получился новый форк.

https://github.com/Zigridar/bitcoin-0.12.1/blob/master/src/chainparams.cpp#L109
https://github.com/Zigridar/bitcoin-0.12.1/blob/master/src/chainparams.cpp#L111
https://github.com/Zigridar/bitcoin-0.12.1/blob/master/src/chainparams.cpp#L112

**Comment by Zigridar** [comment]
Создал новый репозиторий, потому что в этом уже были изменения сделанные мной (к тому же не все верные) до архивирования и они не отображаются в commit, что не очень удобно. https://github.com/Zigridar/bitcoin-v-12.1
Там все исправления оригинального кода уже сохранены в commit
https://github.com/Zigridar/bitcoin-v-12.1/issues/1
